### ISSUE TITLE
[Gradle] Cannot find symbol `qEngine.setClient(httpclient)`

### ISSUE THREAD

**Issue by SkypLabs** [semantic-integration/hypergraphql#19]
Hi there,

I just tried to compile the project using Gradle but I got the following error:

```
/home/gradle/project/src/main/java/org/hypergraphql/datafetching/SPARQLEndpointExecution.java:77: error: cannot find symbol
        qEngine.setClient(httpclient);
               ^
  symbol:   method setClient(HttpClient)
  location: variable qEngine of type QueryEngineHTTP
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

I'm wondering if there is something wrong with the dependencies. I would really appreciate if you could give my a nudge.

Thank you in advance.

**Comment by sklarman** [comment]
Hi,

Indeed, `build.gradle` was outdated. I pushed an update to the `master` branch. Please try it and let me know in case it still fails.

**Comment by SkypLabs** [comment]
It works fine now 👍 Thanks
