### ISSUE TITLE
help with fuseki sparql endpoint

### ISSUE THREAD

**Issue by jeffreycwitt** [semantic-integration/hypergraphql#20]
I'm having trouble hooking up my FUSEKI SPARQL endpoint to hypergraphql.

I wonder if you can help me troubleshoot the problem. 

Here's the config file I'm using

```
{
    "name": "scta-sparql-demo",
    "schema": "schema2.graphql",
    "server": {
        "port": 8080,
        "graphql": "/graphql",
        "graphiql": "/graphiql"
    },
    "services": [
        {
            "id": "scta-sparql",
            "type": "SPARQLEndpointService",
            "url": "http://sparql-staging.scta.info/ds/query",
            "graph": "http://scta.info",
            "user": "",
            "password": ""
        }
    ]
}
```
Here's the very simple schema2.graphql file I made: 

```
type __Context {
    Expression:     _@href(iri: "http://scta.info/resource/expression")
    title:          _@href(iri: "http://purl.org/dc/elements/1.1/title")


}

type Expression @service(id:"scta-sparql") {
    title: [String] @service(id:"scta-sparql")
}
```

And here's the graphql query I'm running

```
query
{
  Expression_GET(limit: 2, offset: 1) {
    _id
  }
}
```
I've had success using a local rdf/xml file, which contains the same data as the endpoint, while using the same the schema and graphql query. 

I've also run successfully the corresponding SPARQL query

```
  SELECT ?expression 
  WHERE {
    ?expression a <http://scta.info/resource/expression> .
  } LIMIT 2 OFFSET 1

```
with success, see: [http://sparql-staging.scta.info/ds/query?query=+SELECT+%3Fexpression+%0D%0A++WHERE+%7B%0D%0A++++%3Fexpression+a+%3Chttp%3A%2F%2Fscta.info%2Fresource%2Fexpression%3E+.%0D%0A++%7D+LIMIT+2+OFFSET+1%0D%0A&output=json&stylesheet=](http://sparql-staging.scta.info/ds/query?query=+SELECT+%3Fexpression+%0D%0A++WHERE+%7B%0D%0A++++%3Fexpression+a+%3Chttp%3A%2F%2Fscta.info%2Fresource%2Fexpression%3E+.%0D%0A++%7D+LIMIT+2+OFFSET+1%0D%0A&output=json&stylesheet=)

graphql is NOT reporting errors, I'm just getting an empty response, 

```
{
  "extensions": {},
  "data": {
    "Expression_GET": [],
    "@context": {
      "_type": "@type",
      "_id": "@id",
      "Expression_GET": "http://hypergraphql.org/query/Expression_GET"
    }
  },
  "errors": []
}
```

even though the above query shows that I should be getting a response with results. 

I really appreciate any help you can send my way.

P.s. Is there any way to see the precise SPARQL query that hypergraphql is sending to the configured endpoint? That would also help me trouble shoot the problem.

**Comment by sklarman** [comment]
Hi Jeffrey,

It seems to me that your data is not actually in the named graph `http://scta.info` but in the default graph. So if you replace this line of your `config.json`:

`"graph": "http://scta.info",`

with

`"graph": "",`

your GraphQL query should return the expected result. Note that you also skip the named graph parameter in your SPARQL queries, which means that you don't really query any specific named graph.

All SPARQL queries that are involved in the process are output into the `logging.log` file. If you'd like to see them also in your console/terminal you should go into the `src\main\java\org\hypergraphql\datafetching\SPARQLEndpointExecution.java` file, and add this line:

`System.out.println(sparqlQuery);` 

under `logger.info(sparqlQuery);`.

Let me know if this works!

Szymon

**Comment by jeffreycwitt** [comment]
Awesome. That fixed things. I knew I was doing something stupid. 

BTW, I really love this project. 

I hope to learn more as I explore and I'm sure I'll have more questions in the future.

**Comment by sklarman** [comment]
Glad to hear that! Good luck and keep in touch if you have any issues or comments.

**Comment by jeffreycwitt** [comment]
`System.out.println(sparqlQuery); ` worked great, but for anyone else implementing this I did have to rerun `mvn install` before it started working :)
