### ISSUE TITLE
Consider using extensions key for context

### ISSUE THREAD

**Issue by kbrandwijk** [semantic-integration/hypergraphql#23]
I love the idea of this project, but I don't like the fact that it returns a non-standard response (with the `@context` key). The graphql spec offers a standard way to implement this, using the `extensions` key.

**Comment by sklarman** [comment]
Hi,

Thanks a lot for your comment! In all honesty, we've been reflecting on this exact issue and (at least for now) decided to go with the current approach. It seems there's a little trade-off involved here. Either you have to slightly depart from the standard GraphQL response (and add that one extra key) or you break the standard JSON-LD structure (by serving the context separately). We thought that the former is overall less harmful as you can always ignore `@context` if you don't need it without putting any extra work. In the latter case, when you do want to use it, you might need to first manipulate JSON to obtain a valid JSON-LD. So none of these strategies is perfect but the current one seems a bit simpler. Unless you see there are more important reasons we should consider apart from GraphQL "purity".

**Comment by pc3356** [comment]
This issue was moved to hypergraphql/hypergraphql#14
