### ISSUE TITLE
Test automatically the building process

### ISSUE THREAD

**Issue by SkypLabs** [semantic-integration/hypergraphql#32]
Hi,

This issue follows up with #29.

I suggest to add a way to test automatically the building process and, if any, to execute all the unit tests in order to track issues in terms of misconfiguration, dependency problem or regression (see #19).

The pull request #29 suggests using Travis CI to carry out this task. Travis CI is a free, open-source and easy-to-use hosted continuous integration and deployment system. It perfectly fits the needs of an open-source project such as HyperGraphQL.

If you have any questions about Travis CI or the continuous integration and deployment systems in general, I would be happy to answer you.

Thanks.

**Comment by pc3356** [comment]
This issue was moved to hypergraphql/hypergraphql#13
