### ISSUE TITLE
DBpedia example: type of Country class

### ISSUE THREAD

**Issue by jgrzebyta** [semantic-integration/hypergraphql#37]
I found DBpedia classified centuries as dbo:Country (proof [here](http://dbpedia.org/sparql/?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=select+distinct+%3Fit%0D%0A%7B%0D%0A%3Fit+a+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FCountry%3E%0D%0A%7D+limit+5&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+) )

The best solution I found is to change type into <http://schema.org/Country>

**Comment by pc3356** [comment]
I'll have a look at the demo, but it's really designed as a simple demonstration, and not intended to be a set of production examples.
