### ISSUE TITLE
Please add an example of a query result with multiple values

### ISSUE THREAD

**Issue by jcoyne** [semantic-integration/hypergraphql#6]
For example:
```ttl
<https://github.com/jcoyne> <foaf:nick> "jcoyne", "j_coyne" .
```

Thanks.

**Comment by sklarman** [comment]
Take a look at this query. It returns multiple values of the predicate *rdfs:label* http://bit.ly/2myKH69. 

In GraphQL schemas you can distinguish directly which fields return a single and which multiple values by using square brackets, e.g.:

```
type Person {
    name: String
    label: [String]
}
```

The definition above means that any instance of type Person can have (at most) one name, but possibly many labels.

**Comment by jcoyne** [comment]
Thanks!

**Comment by jcoyne** [comment]
It seems like imposing a GraphQL schema is the only way that GraphQL could operate, but data in a triplestore may not conform to that schema.  Do you have strategies to ensure that new triples are not causing your graph subjects to become non-conformant to the schema?

**Comment by sklarman** [comment]
> It seems like imposing a GraphQL schema is the only way that GraphQL could operate

Correct.

> but data in a triplestore may not conform to that schema

Correct.

> Do you have strategies to ensure that new triples are not causing your graph subjects to become non-conformant to the schema?

The way we approach it, and generally, the way to think about it is to see GraphQL schema as a "lens" over the RDF data. And through this lens you only see those fragments of the RDF graph that actually do comply with that schema. The rest remains invisible.  

And less metaphorically speaking, if we have the following schema:

```
type Query {
   people: [Person]
}

type Person {
    birthPlace: City
}

type City {
...
}
```

and a mapping:

```
"birthPlace": "dbo:birthPlace",
"Person": "dbo:Person",
"City": "dbo:City"
...
```

then the following GraphQL query:


```
{
   people {
      birthPlace {
      ...
   }
  }
}
```

will be effectively correspond to the following SPARQL query pattern:

```
?x rdf:type dbo:Person . 
OPTIONAL {
   ?x dbo:birthPlace ?y .
   ?y rdf:type dbo:City .
}
...
```

If the actual RDF data doesn't match this pattern, then it is not picked up, and effectively excluded from the GraphQL answers.

Does it make sense?

**Comment by jcoyne** [comment]
Yes, that makes sense, but that means if we do have two values (for rdfs:label) say, then you could see the query return different data each time it's run.  And you'll lose data if you try to write that data from your query back into the triple store (as a full subject replace).

**Comment by sklarman** [comment]
> then you could see the query return different data each time it's run

Good point! If you have multiple labels, yet your GraphQL schema expects a single value for that field, then the choice is inevitably arbitrary. We could make it deterministic, though, using some ordering, to at least avoid randomness... Or perhaps we should always require a list of objects as the output type for all fields in the schema by default...? We'll have to think about it. Thanks for pointing this out!

I'm not sure if I understand your second comment about a full subject replace. Could you elaborate a bit more, please?

**Comment by jcoyne** [comment]
If you have some system for writing back values (SPARQL insert, or LDP PATCH), and you write back values retrieved from GraphQL, and since we don't have a full set of the data, we could unintentionally overwrite multiple values with a single value.

**Comment by sklarman** [comment]
This could happen if you stored JSON-LD in a document store and were replacing it with the result of the query. But if you write triples in an RDF store using SPARQL insert, you can't really "overwrite" content, can you? You just add new triples... But anyways, there's indeed an open issue here to be considered. Thanks.
